%% =========================================================================
%  VERIFY_WAZUH_SIM.M
%  One-click validation script to send test cyber-physical security events
%  from MATLAB to Wazuh SIEM and confirm connection.
%  =========================================================================
clear; clc;

fprintf('=================================================================\n');
fprintf('  TESTING MATLAB -> WAZUH SIEM LIVE INTEGRATION\n');
fprintf('=================================================================\n\n');

% 1. Baseline Telemetry Event
fprintf('[1/4] Sending Normal Operating Telemetry...\n');
wazuh_sender('TELEMETRY_NORMAL', struct( ...
    'status', 'HEALTHY', ...
    'sensor_voltage', 500.0, ...
    'nominal_voltage', 500.0, ...
    'power_kw', 100.0, ...
    'residual', 0.05, ...
    'threshold', 1.20));

% 2. Attack Injection Event
fprintf('[2/4] Sending Cyber Attack Injection (Ramp FDIA)...\n');
wazuh_sender('CYBER_ATTACK_INJECTED', struct( ...
    'attack_type', 'Ramp FDIA (Stealthy)', ...
    'defense_enabled', true, ...
    'attack_start_sec', 2.0, ...
    'nominal_voltage', 500.0, ...
    'sensor_voltage', 525.0));

% 3. Luenberger Observer Residual Alert
fprintf('[3/4] Sending Observer Anomaly Detection Alert...\n');
wazuh_sender('ANOMALY_RESIDUAL_ALERT', struct( ...
    'attack_type', 'Ramp FDIA (Stealthy)', ...
    'residual', 3.85, ...
    'threshold', 1.20, ...
    'time_of_alarm_sec', 2.085, ...
    'detect_delay_ms', 85.0));

% 4. Cyber Resilience Mitigation
fprintf('[4/4] Sending Autonomous Mitigation Action...\n');
wazuh_sender('CYBER_RESILIENCE_MITIGATED', struct( ...
    'attack_type', 'Ramp FDIA (Stealthy)', ...
    'action', 'OBSERVER_ISOLATION_SWITCH', ...
    'status', 'MITIGATED_SECURE'));

fprintf('\n[+] All events dispatched to Wazuh SIEM over UDP port 514!\n');
fprintf('    Check your browser at https://localhost -> Security Events!\n\n');
